### ISSUE TITLE
Index outside of bounds after long-term usage

### ISSUE THREAD

**Issue by peppy** [redhat-developer/kestrel-linux-transport#100]
Had this happen twice on a production deployment that handles thousands of requests per second, only after several days of uptime. If it helps at all, I was also hitting a limit of open file handles a few times after switching to linux transport. Not certain if leak or just high usage (was exceeding 1mil where my app is usually around 180k) but I do plan on investigating that further.

```
Process terminated. TransportThread
   at System.Environment.FailFast(System.String, System.Exception)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread+ThreadContext.Run()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.PollThread(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.AioSend(List`1 sendQueue)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.DoScheduledWork(Boolean aioSend)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()Process terminated. TransportThread
   at System.Environment.FailFast(System.String, System.Exception)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread+ThreadContext.Run()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.PollThread(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.AioSend(List`1 sendQueue)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.DoScheduledWork(Boolean aioSend)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()Process terminated. TransportThread
   at System.Environment.FailFast(System.String, System.Exception)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread+ThreadContext.Run()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.PollThread(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.AioSend(List`1 sendQueue)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.DoScheduledWork(Boolean aioSend)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()Process terminated. TransportThread
   at System.Environment.FailFast(System.String, System.Exception)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread+ThreadContext.Run()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.PollThread(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
```

**Comment by tmds** [comment]
This code is no longer maintained, and won't be updated for new versions of .NET.
I'll archive the repository.
