### ISSUE TITLE
2.1.0-preview1 - exception on exit

### ISSUE THREAD

**Issue by AerisG222** [redhat-developer/kestrel-linux-transport#62]
I just tried the Linux Transport, and seems to be working pretty well. I haven't noticed any issues so far serving content out of kestrel over https - nice work!  

However, I often see the following exception when killing the kestrel instance via `ctl-c`:

```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unexpected exception in HttpConnection.ProcessRequestsAsync.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MemoryPoolBlock'.
   at System.Buffers.ThrowHelper.ThrowObjectDisposedException(ExceptionArgument argument)
   at System.Buffers.MemoryPoolBlock.Dispose()
   at System.IO.Pipelines.BufferSegment.ResetMemory()
   at System.IO.Pipelines.Pipe.CompletePipe()
   at System.IO.Pipelines.Pipe.CompleteWriter(Exception exception)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.Complete(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.AdaptedPipeline.ReadInputAsync(Stream stream)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.AdaptedPipeline.RunAsync(Stream stream)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
```
This sometimes is emitted multiple times as part of the same process being killed.

Here is the output of `dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     fedora
 OS Version:  28
 OS Platform: Linux
 RID:         fedora.28-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Thanks

**Comment by tmds** [comment]
@AerisG222 Thanks for giving it a try and providing feedback!

This exception should no longer be thrown with ASP.NET Core 2.1.3 due to this change: https://github.com/aspnet/Common/pull/381. Can you try using the 2.1.3 version?

I'll look if there is something that can be improved so this doesn't throw with 2.1.2 either.

**Comment by AerisG222** [comment]
Thanks @tmds for the quick response.

Is there an easy way to install 2.1.3?

If it is going to be out soon, which was my understanding, I will just wait and give it a test then.

**Comment by AerisG222** [comment]
@tmds: I just saw the notes on how to test out 2.1.3 - and the Linux Transport worked great!  I have not been able to reproduce the exceptions when killing Kestrel.

Thanks

**Comment by tmds** [comment]
Thanks for verifying!
