### ISSUE TITLE
Getting Method Not Found Error

### ISSUE THREAD

**Issue by 54mv39** [redhat-developer/kestrel-linux-transport#77]
I am trying to use linux  transport, Here are the details:
Platform: kestrel server with reverse proxy on Ubuntu 16.04
**Program.cs**
<return WebHost.CreateDefaultBuilder(args)
                  .ConfigureLogging(builder => builder.AddFile(options =>
                  {
                      options.FileName = "diagnostics-"; // The log file prefixes
                      options.LogDirectory = "LogFiles"; // The directory to write the logs
                      options.FileSizeLimit = 20 * 1024 * 1024; // The maximum log file size (20MB here)
                      options.Extension = "txt"; // The log file extension
                  }))
                   .UseLinuxTransport()
                   .UseStartup<Startup>();>
**ERROR:**
<Method not found: 'Void Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.IConnectionDispatcher.OnConnection(Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.TransportConnection)'.
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.HandleAccept(TSocket tacceptSocket)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()
FailFast:
TransportThread

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread+ThreadContext.Run()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.PollThread(System.Object)
   at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

Exception details:
System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.IConnectionDispatcher.OnConnection(Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.TransportConnection)'.
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.HandleAccept(TSocket tacceptSocket)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()
>

**Comment by 54mv39** [comment]
duplicate of #78
