### ISSUE TITLE
localhost + Docker development problem to bind IPv6 and IPv4 - throw IOException

### ISSUE THREAD

**Issue by lillo42** [redhat-developer/kestrel-linux-transport#91]
Hi,

I'm trying to use ASP.NET Core with Linux Transport fail  but when I run my project, ASP.NET Core fail to start:

[project.zip](https://github.com/redhat-developer/kestrel-linux-transport/files/3715992/WebAppLinux2.zip)

Call Stack:

```crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: EADDRNOTAVAIL
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.PosixResult.ThrowException()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.TSocket.Bind(IPEndPointStruct endpoint)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.CreateAcceptSocket(IPEndPoint endPoint, SocketFlags flags)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Start()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()
--- End of stack trace from previous location where exception was thrown ---
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
```

Full call stack:
```
root@d24828eef097:/workspaces/WebAppLinux2# dotnet run
Using launch settings from /workspaces/WebAppLinux2/Properties/launchSettings.json...
: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
      Creating key {10ca567a-54dd-44d7-8e26-e7847585a08c} with creation date 2019-10-11 06:44:21Z, activation date 2019-10-11 06:44:21Z, and expiration date 2020-01-09 06:44:21Z.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {10ca567a-54dd-44d7-8e26-e7847585a08c} may be persisted to storage in unencrypted form.
info: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
      Writing data to file '/root/.aspnet/DataProtection-Keys/key-10ca567a-54dd-44d7-8e26-e7847585a08c.xml'.
dbug: RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport[0]
      BindAsync https://127.0.0.1:5001: TC:4 TA:False IC:False DA:False
dbug: RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport[0]
      BindAsync https://[::1]:5001: TC:4 TA:False IC:False DA:False
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: EADDRNOTAVAIL
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.PosixResult.ThrowException()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.TSocket.Bind(IPEndPointStruct endpoint)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.CreateAcceptSocket(IPEndPoint endPoint, SocketFlags flags)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Start()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()
--- End of stack trace from previous location where exception was thrown ---
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
dbug: RedHat.TransportThread.3[0]
      Stats A/AE:0/0 RE:0 WE:0 ZCS/ZCC:0/0
dbug: RedHat.TransportThread.2[0]
      Stats A/AE:0/0 RE:0 WE:0 ZCS/ZCC:0/0
dbug: RedHat.TransportThread.4[0]
      Stats A/AE:0/0 RE:0 WE:0 ZCS/ZCC:0/0
dbug: RedHat.TransportThread.1[0]
      Stats A/AE:0/0 RE:0 WE:0 ZCS/ZCC:0/0

Unhandled Exception: System.IO.IOException: EADDRNOTAVAIL
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.PosixResult.ThrowException()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.TSocket.Bind(IPEndPointStruct endpoint)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.CreateAcceptSocket(IPEndPoint endPoint, SocketFlags flags)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Start()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()
--- End of stack trace from previous location where exception was thrown ---
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at WebAppLinux2.Program.Main(String[] args) in /workspaces/WebAppLinux2/Program.cs:line 17
```

**Comment by lillo42** [comment]
@tmds do you have any idea what could be this error? I'm using ASP.NET Core 2.1 + VS Code + Remote Development

**Comment by tmds** [comment]
EADDRNOTAVAIL means the address is not available. Is another application using port 5001?

**Comment by lillo42** [comment]
No, if run remove ```UseLinuxTransport()``` work.

**Comment by tmds** [comment]
> No, if run remove UseLinuxTransport() work.

That's interesting. The project runs fine with UseLinuxTransport here.

Can you share the output of `strace -qq -f -e  bind dotnet bin/Debug/netcoreapp2.1/WebAppLinux2.dll` ?

**Comment by lillo42** [comment]
If I use the command below works:
```bash
dotnet bin/Debug/netcoreapp2.1/WebAppLinux2.dll
```
strace:
```bash
root@74ccadfd8097:/workspaces/WebAppLinux2# strace -qq -f -e bind dotnet bin/Debug/netcoreapp2.1/WebAppLinux2.dll
[pid  6144] bind(169, {sa_family=AF_INET6, sin6_port=htons(80), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
[pid  6147] bind(168, {sa_family=AF_INET6, sin6_port=htons(80), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28 <unfinished ...>
[pid  6145] bind(171, {sa_family=AF_INET6, sin6_port=htons(80), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
[pid  6147] <... bind resumed> )        = 0
[pid  6146] bind(170, {sa_family=AF_INET6, sin6_port=htons(80), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
Hosting environment: Production
Content root path: /workspaces/WebAppLinux2
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```
but if I use this command:
```bash
dotnet run 
```
strace:
```bash
root@74ccadfd8097:/workspaces/WebAppLinux2# strace -qq -f -e bind dotnet run                                                                                                               [pid  5630] bind(102, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
[pid  5632] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5646, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
[pid  5650] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5655, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
[pid  5641] bind(110, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
[pid  5616] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5632, si_uid=0, si_status=0, si_utime=145, si_stime=48} ---
[pid  5616] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5660, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
Using launch settings from /workspaces/WebAppLinux2/Properties/launchSettings.json...
: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
dbug: RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport[0]
      BindAsync https://127.0.0.1:5001: TC:4 TA:False IC:False DA:False
[pid  5688] bind(177, {sa_family=AF_INET, sin_port=htons(5001), sin_addr=inet_addr("127.0.0.1")}, 16 <unfinished ...>
[pid  5686] bind(175, {sa_family=AF_INET, sin_port=htons(5001), sin_addr=inet_addr("127.0.0.1")}, 16 <unfinished ...>
[pid  5688] <... bind resumed> )        = 0
[pid  5686] <... bind resumed> )        = 0
[pid  5687] bind(176, {sa_family=AF_INET, sin_port=htons(5001), sin_addr=inet_addr("127.0.0.1")}, 16 <unfinished ...>
[pid  5685] bind(178, {sa_family=AF_INET, sin_port=htons(5001), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
[pid  5687] <... bind resumed> )        = 0
dbug: RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport[0]
      BindAsync https://[::1]:5001: TC:4 TA:False IC:False DA:False
[pid  5689] bind(185, {sa_family=AF_INET6, sin6_port=htons(5001), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Cannot assign requested address)
[pid  5690] bind(187, {sa_family=AF_INET6, sin6_port=htons(5001), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Cannot assign requested address)
[pid  5691] bind(185, {sa_family=AF_INET6, sin6_port=htons(5001), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Cannot assign requested address)
[pid  5692] bind(184, {sa_family=AF_INET6, sin6_port=htons(5001), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Cannot assign requested address)
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: EADDRNOTAVAIL
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.PosixResult.ThrowException()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.TSocket.Bind(IPEndPointStruct endpoint)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.CreateAcceptSocket(IPEndPoint endPoint, SocketFlags flags)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Start()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()
--- End of stack trace from previous location where exception was thrown ---
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
dbug: RedHat.TransportThread.3[0]
      Stats A/AE:0/0 RE:0 WE:0 ZCS/ZCC:0/0
dbug: RedHat.TransportThread.4[0]
      Stats A/AE:0/0 RE:0 WE:0 ZCS/ZCC:0/0
dbug: RedHat.TransportThread.2[0]
      Stats A/AE:0/0 RE:0 WE:0 ZCS/ZCC:0/0
dbug: RedHat.TransportThread.1[0]
      Stats A/AE:0/0 RE:0 WE:0 ZCS/ZCC:0/0

Unhandled Exception: System.IO.IOException: EADDRNOTAVAIL
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.PosixResult.ThrowException()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.TSocket.Bind(IPEndPointStruct endpoint)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.CreateAcceptSocket(IPEndPoint endPoint, SocketFlags flags)
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Start()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.TransportThread.ThreadContext.Run()
--- End of stack trace from previous location where exception was thrown ---
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at RedHat.AspNetCore.Server.Kestrel.Transport.Linux.Transport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at WebAppLinux2.Program.Main(String[] args) in /workspaces/WebAppLinux2/Program.cs:line 17
[pid  5661] --- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=5661, si_uid=0} ---
[pid  5688] +++ killed by SIGABRT (core dumped) +++
[pid  5687] +++ killed by SIGABRT (core dumped) +++
[pid  5686] +++ killed by SIGABRT (core dumped) +++
[pid  5685] +++ killed by SIGABRT (core dumped) +++
[pid  5683] +++ killed by SIGABRT (core dumped) +++
[pid  5684] +++ killed by SIGABRT (core dumped) +++
[pid  5682] +++ killed by SIGABRT (core dumped) +++
[pid  5681] +++ killed by SIGABRT (core dumped) +++
[pid  5679] +++ killed by SIGABRT (core dumped) +++
[pid  5677] +++ killed by SIGABRT (core dumped) +++
[pid  5676] +++ killed by SIGABRT (core dumped) +++
[pid  5675] +++ killed by SIGABRT (core dumped) +++
[pid  5674] +++ killed by SIGABRT (core dumped) +++
[pid  5673] +++ killed by SIGABRT (core dumped) +++
[pid  5672] +++ killed by SIGABRT (core dumped) +++
[pid  5671] +++ killed by SIGABRT (core dumped) +++
[pid  5670] +++ killed by SIGABRT (core dumped) +++
[pid  5669] +++ killed by SIGABRT (core dumped) +++
[pid  5668] +++ killed by SIGABRT (core dumped) +++
[pid  5667] +++ killed by SIGABRT (core dumped) +++
[pid  5666] +++ killed by SIGABRT (core dumped) +++
[pid  5665] +++ killed by SIGABRT (core dumped) +++
[pid  5664] +++ killed by SIGABRT (core dumped) +++
[pid  5661] +++ killed by SIGABRT (core dumped) +++
[pid  5616] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=5661, si_uid=0, si_status=SIGABRT, si_utime=59, si_stime=14} ---
```

**Comment by lillo42** [comment]
Now I realize, when I run the command:
```bash
root@74ccadfd8097:/workspaces/WebAppLinux2# dotnet run
Using launch settings from /workspaces/WebAppLinux2/Properties/launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to https://localhost:5001 on the IPv6 loopback interface: 'Cannot assign requested address'.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Cannot assign requested address'.
Hosting environment: Development
Content root path: /workspaces/WebAppLinux2
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

The default .NET Socket didn't bin IPv6 too, but just a warning

**Comment by lillo42** [comment]
Look this code in ASP.NET Core:

https://github.com/aspnet/AspNetCore/blob/4dd9bfc492452174f9329c3e1fc4807cb393c05a/src/Servers/Kestrel/Core/src/LocalhostListenOptions.cs#L33-L67

if we change this exception for something different the  System.IO.IOException will work, I think
